---
- name: tap for ricty
  homebrew_tap:
      tap: sanemat/font
      state: present

#brew reinstall with-powerline --vim-powerline ricty
- name: install ricty
  homebrew:
    name: ricty
    state: latest
    install_options: with-powerline,vim-powerline

- name: copy fonts
  copy:
    src: "{{ item }}"
    dest: ~/Library/Fonts/
  with_fileglob:
    - /usr/local/opt/ricty/share/fonts/Ricty*.ttf
  notify: run fc-cache