---
    # Tap external Homebrew Cask repositories.
    homebrew_cask_repositories:
      - caskroom/versions

    # Managed Homebrew Cask packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state }
    #
    # state choices: [present, absent, installed, uninstalled] (default: present)
    homebrew_cask_packages:
      - alfred
      - appcleaner
      - atom
      - caffeine
      - chromium
      - clipy
      - coteditor
      - dash
      - datagrip
      - dropbox
      - evernote
      - firefox
      - flash
      - flash-player
      - flux
      - franz
      - github-desktop
      - google-chrome
      - google-chrome-canary
      - google-japanese-ime
      - google-photos-backup
      - iterm2
      - java6
      - karabiner
      - keepassx
      - magican
      - mysqlworkbench
      - p4merge
      - phpstorm
      - postman
      - rdm
      - sequel-pro
      - slack
      - sourcetree
      - sublime-text
      - the-unarchiver
      - unetbootin
      - vagrant
      - virtualbox
      - visual-studio-code
      - vivaldi
      - vlc
