---
    # Tap external Homebrew repositories.
    #
    # e.g.
    # - homebrew/binary
    homebrew_repositories:
      - argon/mas
      - homebrew/completions
      - homebrew/core
      - homebrew/dupes
      - homebrew/php
    # Managed Homebrew packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
    #
    # state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
    # install_options: string or sequence (default: none)
    homebrew_packages:
      - autoconf
      - automake
      - bash-completion
      - bison
      - bzip2
      - curl
      - direnv
      - fish
      - freetype
      - gdbm
      - gettext
      - git
      - gmp
      - httpie
      - hub
      - icu4c
      - jpeg
      - jq
      - libevent
      - libpng
      - libtool
      - libxml2
      - libyaml
      - mackup
      - mas
      - mcrypt
      - mhash
      - nodebrew
      - oniguruma
      - openssl
      - { name: openssl, state: linked, install_options: force }
      - pcre
      - pcre2
      - peco
      - php70
      - phpbrew
      - pkg-config
      - rbenv
      - re2c
      - readline
      - ruby-build
      - the_silver_searcher
      - tig
      - tree
      - unixodbc
      - vagrant-completion
      - vim
      - wget
      - xz
      - zlib
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
